replicaCount: 3
namespace: helmtest
image:
  repository: thechetantalwar/php
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
